[[main]]
name = "whoami"
pageRef = "/content/whoami/"
weight = 1

[[main]]
name = "blog"
pageRef = "/content/posts/"
weight = 2

[[main]]
name = "writeups"
pageRef = "/content//writeups/"
weight = 3

